package main.resumeProcessor;

public enum TokenType{
	NAME, ADDRESS, URL_HEADER, URL, PHONE, EMAIL, 
	EDUCATION, EXPERIENCE, SKILLS,
	ALPHA, NUMERIC, ALPHA_NUMERIC, 
	EOF, 
	
	MONTH_STRING, YEAR, PRESENT, PROJECTS, PERSONAL, MONTH_YEAR, DATE, ACHIEVMENTS, REFERENCES  
}